package view;

import control.ClientCtr;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author Tuan-user
 */
public class FriendFrm extends javax.swing.JFrame {

    private User user;
    private ClientCtr mySocket;
    private ArrayList<User> list;

    /**
     * Creates new form FriendFrm
     */
    public FriendFrm(User user, ClientCtr mySocket) {
        this.user = user;
        this.mySocket = mySocket;
        initComponents();

        getFriendList();
        mySocket.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REFRESH, this));
        mySocket.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_SEARCH_FRIEND, this));
        mySocket.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_SEARCH_USER, this));
        mySocket.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_FRIEND_REQUEST, this));
    }

    private DefaultTableModel convert2TableModel(ObjectWrapper data) {
        list = (ArrayList<User>) data.getData();
        String[] columNames = {"ID", "User name", "Name", "Telephone", "Status"};
        String[][] value = new String[list.size()][5];
        for (int i = 0; i < list.size(); i++) {
            value[i][0] = Integer.toString(list.get(i).getUser_id());
            value[i][1] = list.get(i).getUser_name();
            value[i][2] = list.get(i).getName();
            value[i][3] = list.get(i).getTel();
            value[i][4] = list.get(i).getStatus();
        }
        DefaultTableModel tm = new DefaultTableModel(value, columNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        return tm;
    }

    public void fillFriendList(ObjectWrapper data) { //fill data to jatble1
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);

        jTable1.setModel(convert2TableModel(data));
//        jTable1.getTableHeader().setResizingAllowed(false);
    }

    public void displayFriendRequest(ObjectWrapper data) { //fill data to jtable3
        DefaultTableModel tableModel = (DefaultTableModel) jTable3.getModel();
        tableModel.setRowCount(0);

        jTable3.setModel(convert2TableModel(data));

    }

    public void fillUserList(ObjectWrapper data) {   //fill data to jtable2
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        tableModel.setRowCount(0);

        jTable2.setModel(convert2TableModel(data));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        friendPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        unFriendBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        addFriendBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        acceptBtn = new javax.swing.JButton();
        ignoreBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        friendPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        friendPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        friendPane.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        friendPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                friendPaneStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Friend List");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        unFriendBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        unFriendBtn.setText("Unfriend");
        unFriendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unFriendBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(unFriendBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(unFriendBtn)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        friendPane.addTab("Friend List", jPanel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search Friend");

        txtKey.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        searchBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setToolTipText("");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        addFriendBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addFriendBtn.setText("Add Friend");
        addFriendBtn.setToolTipText("");
        addFriendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(addFriendBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addFriendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        friendPane.addTab("Search", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Friend Request");

        acceptBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        acceptBtn.setText("Accept");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        ignoreBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ignoreBtn.setText("Ignore");
        ignoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignoreBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(acceptBtn)
                        .addGap(131, 131, 131)
                        .addComponent(ignoreBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ignoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        friendPane.addTab("FriendRequest", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(friendPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(friendPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        if ((txtKey.getText() == null) || (txtKey.getText().length() == 0)) {
            mySocket.sendData(new ObjectWrapper(ObjectWrapper.SEARCH_ALL_USER, user));
        } else {
            mySocket.sendData(new ObjectWrapper(ObjectWrapper.SEARCH_USER_BY_NAME, txtKey.getText().trim()));
        }
        mySocket.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_SEARCH_USER, this));

    }//GEN-LAST:event_searchBtnActionPerformed

    public void getFriendList() {
        mySocket.sendData(new ObjectWrapper(ObjectWrapper.SEARCH_FRIEND, user));
    }

    public void getUserList() {
        mySocket.sendData(new ObjectWrapper(ObjectWrapper.SEARCH_ALL_USER, user));
    }

    public void getRequestList() {
        mySocket.sendData(new ObjectWrapper(ObjectWrapper.FRIEND_REQUEST, user));
    }

    private void friendPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_friendPaneStateChanged
        int index = friendPane.getSelectedIndex();
        if (index == 0) {
            getFriendList();
        } else if (index == 1) {
            getUserList();
//            System.out.println("363-friendFrm: " + user.getUser_id());
        } else if (index == 2) {
            getRequestList();
        }
    }//GEN-LAST:event_friendPaneStateChanged

    private void unFriendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unFriendBtnActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chọn người để xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);

        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Ban chac chan muon xoa khong?");

            if (confirm == JOptionPane.YES_OPTION) {

                User user2 = new User();
                user2.setUser_id(Integer.valueOf(String.valueOf(jTable1.getValueAt(row, 0))));
//                user2.setName(String.valueOf(jTable1.getValueAt(row, 2)));
//                user2.setUser_name(String.valueOf(jTable1.getValueAt(row, 1)));
//                user2.setTel(String.valueOf(jTable1.getValueAt(row, 3)));
//                user2.setStatus(String.valueOf(jTable1.getValueAt(row, 4)));
                System.out.println("friend 378: " + user2.getUser_id());
                Friend pair = new Friend(user, user2);
                mySocket.sendData(new ObjectWrapper(ObjectWrapper.DELETE_FRIEND, pair));

            }
        }
    }//GEN-LAST:event_unFriendBtnActionPerformed

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        int row = jTable3.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chon người để đồng ý", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            User user2 = new User();
            user2.setUser_id(Integer.valueOf(String.valueOf(jTable3.getValueAt(row, 0))));
//            System.out.println(friendId);
            Friend pair = new Friend(user2, user);
            mySocket.sendData(new ObjectWrapper(ObjectWrapper.ACCEPT_FRIEND_REQUEST, pair));
            getFriendList();
        }
    }//GEN-LAST:event_acceptBtnActionPerformed

    private void ignoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignoreBtnActionPerformed
        int row = jTable3.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chon người để thao tác", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            User user2 = new User();
            user2.setUser_id(Integer.valueOf(String.valueOf(jTable3.getValueAt(row, 0))));
            
            Friend pair = new Friend(user2, user);
            mySocket.sendData(new ObjectWrapper(ObjectWrapper.IGNORE_FRIEND_REQUEST, pair));
        }
    }//GEN-LAST:event_ignoreBtnActionPerformed

    public void showResult(String input) {
        if (input.equals("done")) {
            JOptionPane.showMessageDialog(this, "Gửi lời mời kết bạn thành công!");
        } else if (input.equals("sent")) {
            JOptionPane.showMessageDialog(this, "Lời mời đã được gửi", "Gửi không thành công", JOptionPane.ERROR_MESSAGE);
        } else if (input.equals("friend")) {
            JOptionPane.showMessageDialog(this, "Hai người đã là bạn", "Gửi không thành công", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi! Không gửi được lời mời", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void addFriendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendBtnActionPerformed
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Chon người để kết bạn", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            User user2 = new User();
            user2.setUser_id(Integer.valueOf(String.valueOf(jTable2.getValueAt(row, 0))));
            user2.setName(String.valueOf(jTable2.getValueAt(row, 2)));
            user2.setUser_name(String.valueOf(jTable2.getValueAt(row, 1)));
            user2.setTel(String.valueOf(jTable2.getValueAt(row, 3)));
            user2.setStatus(String.valueOf(jTable2.getValueAt(row, 4)));

            Friend pair = new Friend(user, user2);

            mySocket.sendData(new ObjectWrapper(ObjectWrapper.SEND_FRIEND_REQUEST, pair));
            
        }
    }//GEN-LAST:event_addFriendBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton addFriendBtn;
    private javax.swing.JTabbedPane friendPane;
    private javax.swing.JButton ignoreBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField txtKey;
    private javax.swing.JButton unFriendBtn;
    // End of variables declaration//GEN-END:variables
}
